entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: albertojahueymoncada@gmail.com
      storage: /certs/acme.json
      tlsChallenge: {}

providers:
  docker:
    exposedByDefault: false

api:
  dashboard: false
