#cloud-config
package_update: true
packages:
  - ca-certificates
  - curl
  - git

runcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo $VERSION_CODENAME) stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - sysctl -w net.ipv4.ip_forward=1
  - sysctl -w net.ipv6.conf.all.forwarding=1
  - echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.d/99-tailscale.conf
  - echo 'net.ipv6.conf.all.forwarding=1' >> /etc/sysctl.d/99-tailscale.conf
  - iptables -t nat -A POSTROUTING -s 100.64.0.0/10 -o eth0 -j MASQUERADE
  - ip6tables -t nat -A POSTROUTING -s fd7a:115c:a1e0::/48 -o eth0 -j MASQUERADE
  - systemctl enable docker
  - systemctl start docker
  - systemctl disable --now systemd-resolved
  - rm -f /etc/resolv.conf
  - echo "nameserver 1.1.1.1" > /etc/resolv.conf
  - git clone https://github.com/AJahueyM/Porebazu.git /opt/porebazu
  - docker compose --project-directory /opt/porebazu/vpn -f /opt/porebazu/vpn/docker-compose.yml up -d