#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose-v2
  - git

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - openssl rand -base64 24 >> /opt/porebazu/vpn/headplane/cookie_secret
  - git clone https://github.com/AJahueyM/Porebazu.git /opt/porebazu
  - docker compose --project-directory /opt/porebazu/vpn -f /opt/porebazu/vpn/docker-compose.yml up -d
